# Generated by Django 6.0.2 on 2026-02-20 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('segmento', models.CharField(max_length=100, verbose_name='Segmento')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plano', verbose_name='Plano')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
