# Generated by Django 6.0.2 on 2026-02-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_empresa', '0001_initial'),
        ('core', '0002_permissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_empresa.empresa', verbose_name='Empresa')),
                ('permissoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permissao', verbose_name='Permissões')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
