# Generated by Django 6.0.2 on 2026-02-22 14:40

import django.db.models.deletion
import smart_selects.db_fields
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_empresa', '0003_funcionario_avatar_ativologico'),
        ('core', '0003_nivelcriticidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativologico',
            name='nivel_criticidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.nivelcriticidade', verbose_name='Nível de criticidade'),
        ),
        migrations.CreateModel(
            name='AtivoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Nome do fabricante')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, verbose_name='Número de série')),
                ('data_aquisicao', models.DateField(verbose_name='Data de aquisição')),
                ('data_encerramento_garantia', models.DateField(verbose_name='Data de encerramento do suporte')),
                ('data_ult_manutencao', models.DateField(blank=True, null=True, verbose_name='Data da última manutenção')),
                ('foto_ativo', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='foto_ativo', variations={'thumb': (200, 200)}, verbose_name='Foto do ativo')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_empresa.empresa', verbose_name='Empresa')),
                ('nivel_criticidade', models.ForeignKey(default='Normal', on_delete=django.db.models.deletion.CASCADE, to='core.nivelcriticidade', verbose_name='Nível de criticidade')),
                ('responsavel', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='empresa', chained_model_field='empresa', on_delete=django.db.models.deletion.CASCADE, to='cadastro_empresa.funcionario', verbose_name='Responsável')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
