# Generated by Django 6.0.2 on 2026-02-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_empresa', '0004_ativologico_nivel_criticidade_ativofisico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativofisico',
            name='nivel_criticidade',
        ),
        migrations.RemoveField(
            model_name='ativologico',
            name='nivel_criticidade',
        ),
    ]
