# Generated by Django 6.0.2 on 2026-02-22 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_empresa', '0005_remove_ativofisico_nivel_criticidade_and_more'),
        ('core', '0003_nivelcriticidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativofisico',
            name='nivel_criticidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.nivelcriticidade', verbose_name='Nível de criticidade'),
        ),
        migrations.AddField(
            model_name='ativologico',
            name='nivel_criticidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.nivelcriticidade', verbose_name='Nível de criticidade'),
        ),
    ]
