# Generated by Django 6.0.2 on 2026-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_empresa', '0006_ativofisico_nivel_criticidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativologico',
            name='cpe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPE'),
        ),
        migrations.AddField(
            model_name='ativologico',
            name='produto',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Produto'),
        ),
    ]
