# Generated by Django 6.0.2 on 2026-02-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_empresa', '0007_ativologico_cpe_ativologico_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativologico',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de série'),
        ),
    ]
