# Generated by Django 6.0.2 on 2026-02-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_empresa', '0008_alter_ativologico_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativologico',
            name='cpe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CPE (Reconmendado)'),
        ),
        migrations.AlterField(
            model_name='ativologico',
            name='data_encerramento_suporte',
            field=models.DateField(blank=True, null=True, verbose_name='Data de encerramento do suporte'),
        ),
    ]
