# Generated by Django 6.0.2 on 2026-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_empresa', '0009_alter_ativologico_cpe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativofisico',
            name='modelo',
        ),
        migrations.AddField(
            model_name='ativofisico',
            name='produto',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='ativofisico',
            name='versao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Versão'),
        ),
    ]
