# Generated by Django 6.0.2 on 2026-02-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_empresa', '0010_remove_ativofisico_modelo_ativofisico_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativofisico',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de série'),
        ),
    ]
