# Generated by Django 6.0.2 on 2026-02-22 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_empresa', '0007_ativologico_cpe_ativologico_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('severidade', models.CharField(max_length=50)),
                ('data_identificacao', models.DateField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_empresa.ativologico')),
            ],
        ),
    ]
