# Generated by Django 6.0.2 on 2026-02-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_vulnerabilidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilidade',
            name='data_identificacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
