# Generated by Django 6.0.2 on 2026-02-22 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_vulnerabilidade', '0002_alter_vulnerabilidade_data_identificacao'),
        ('cadastro_empresa', '0011_alter_ativofisico_numero_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerabilidade',
            name='ativo',
        ),
        migrations.AddField(
            model_name='vulnerabilidade',
            name='ativo_fisico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro_empresa.ativofisico'),
        ),
        migrations.AddField(
            model_name='vulnerabilidade',
            name='ativo_logico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro_empresa.ativologico'),
        ),
    ]
